version: '3.9'
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dima
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=games_db
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn games_catalog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/static/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A games_catalog worker -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - redis
  celery-beat:
    build: .
    command: celery -A games_catalog beat -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - redis
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static/
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: