# Generated by Django 3.1.7 on 2021-04-11 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 11, 17, 50, 44, 731062, tzinfo=utc)),
        ),
    ]
