# Generated by Django 3.1.7 on 2021-04-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210424_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='users_added',
            field=models.IntegerField(default=0),
        ),
    ]
