# Generated by Django 3.1.7 on 2021-04-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_mustgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='mustgame',
            name='users_added',
            field=models.IntegerField(default=0),
        ),
    ]
